---
abstract: 'Win32 Console .NET interface'
author:
  - 'J. Schneider'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0.43'
  Test::More: '1.001006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Console-DotNet
no_index:
  directory:
    - t
    - inc
requires:
  Class::Method::Modifiers: '2.11'
  Class::Tiny: '1.000'
  Class::Tiny::Antlers: '0.024'
  Devel::StrictMode: '0.003'
  English: 1.06_01
  List::Util: '0.204'
  PerlX::Assert: '0.905'
  Type::Nano: '0.014'
  Win32: '0.54'
  Win32::API: '0.79'
  Win32::Console: '0.10'
  Win32API::File: '0.1201'
  constant: '1.27'
  namespace::sweep: '0.006'
  perl: '5.014'
resources:
  bugtracker: https://github.com/brickpool/Console/issues
  homepage: http://brickpool.de
  repository: https://github.com/brickpool/Console.git
version: 0.002_000
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
