---
abstract: 'Win32 Console .NET interface'
author:
  - 'J. Schneider'
build_requires:
  ExtUtils::MakeMaker: '0'
  FindBin: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Test::Exception: '0.43'
  Test::More: '1.001006'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Console-DotNet
no_index:
  directory:
    - t
    - inc
recommends:
  DateTime: '0'
  Time::HiRes: '0'
  Type::Tiny: '0'
requires:
  Class::Method::Modifiers: '2.11'
  Class::Tiny: '1.000'
  Class::Tiny::Antlers: '0.024'
  Devel::StrictMode: '0.003'
  English: '0'
  Exporter: '0'
  IO::File: '0'
  IO::Handle: '0'
  IO::Null: '1.01'
  List::Util: '0'
  PerlX::Assert: '0.905'
  Symbol: '0'
  Type::Nano: '0.014'
  Win32: '0.54'
  Win32::API: '0.79'
  Win32::Console: '0.10'
  Win32API::File: '0.1201'
  constant: '0'
  namespace::sweep: '0.006'
  perl: '5.014'
  strict: '0'
  threads: '0'
  threads::shared: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/brickpool/Win32-Console-DotNet/issues
  repository: https://github.com/brickpool/Win32-Console-DotNet.git
version: 0.003_000
x_homepage: http://brickpool.de
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
